use [41practic20]

CREATE TABLE UnitsOfMeasurement(
Id_unit INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Unit NVARCHAR(5) NOT NULL)

CREATE TABLE Categories(
Id_category INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Category NVARCHAR(50) NOT NULL)

CREATE TABLE Manufacturers(
Id_manufacturer INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Manufacturer NVARCHAR(50) NOT NULL)

CREATE TABLE Suppliers(
Id_supplier INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Supplier NVARCHAR(50) NOT NULL)

CREATE TABLE Statuses(
Id_status INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
[Status] NVARCHAR(20))